name: gherkin_widget_extension
description: An extension of gherkin package for widgets
version: 0.0.1
homepage: https://github.com/sncf-connect-tech/gherkin_widget_extension

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  glob: ^2.1.1
  gherkin: ^2.0.8
  logger: ^1.1.0
  xml: ^6.0.1
  path: ^1.8.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
